# Generated by Django 3.1.2 on 2021-12-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('numer_student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('Marks', models.IntegerField()),
            ],
        ),
    ]
