# Generated by Django 3.1.2 on 2021-12-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='subject',
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.state', verbose_name='name'),
        ),
    ]
